{
  try {
    return func.inTransaction(this,null);
  }
 catch (  Exception e) {
    Assert.fail(e.toString());
    return null;
  }
}
