{
  try {
    callback.doTest();
    Assert.fail("Failed to catch exception " + code);
  }
 catch (  SubscriptionRepairException e) {
    assertEquals(e.getCode(),code.getCode());
  }
}
