{
  try {
    await().atMost(5,SECONDS).until(callable);
  }
 catch (  Exception e) {
    Assert.fail("Exception in TestAnalyticsService",e);
  }
}
